"""create variable and system tables

Revision ID: 004abe81f683
Revises: 8f15b294bddc
Create Date: 2023-11-22 05:37:10.479120

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '004abe81f683'
down_revision: Union[str, None] = '8f15b294bddc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('system',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_system_id'), 'system', ['id'], unique=False)
    op.create_index(op.f('ix_system_name'), 'system', ['name'], unique=False)
    op.create_table('variable',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('system_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['system_id'], ['system.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_variable_id'), 'variable', ['id'], unique=False)
    op.create_index(op.f('ix_variable_name'), 'variable', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_variable_name'), table_name='variable')
    op.drop_index(op.f('ix_variable_id'), table_name='variable')
    op.drop_table('variable')
    op.drop_index(op.f('ix_system_name'), table_name='system')
    op.drop_index(op.f('ix_system_id'), table_name='system')
    op.drop_table('system')
    # ### end Alembic commands ###
